Config.FurnitureCatagories = 
{Decorations = {{name = "apa_mp_h_acc_bottle_01", title = "Bottle", price = 700},
                {name = "apa_mp_h_acc_candles_01", title = "Candles", price = 700},
                {name = "p_int_jewel_mirror", title = "Mirror", price = 700},
                {name = "apa_mp_h_acc_dec_plate_01", title = "Decorative Plate", price = 700},
                {name = "apa_mp_h_acc_vase_01", title = "Vase", price = 700},
                {name = "v_res_desktidy", title = "Desk Supplies", price = 700},
                {name = "ex_prop_ashtray_luxe_02", title = "Ashtray", price = 700},
                {name = "v_res_mp_ashtrayb", title = "Ashtray 2", price = 300},
                {name = "prop_bong_01", title = "Bong", price = 700},
                {name = "prop_mr_rasberryclean", title = "Mr Rasberry Clean", price = 700},
                {name = "prop_acc_guitar_01", title = "Guitar", price = 1000},
                {name = "p_planning_board_04", title = "Planning Board", price = 500},
                {name = "prop_hotel_clock_01", title = "Hotel Clock", price = 500},
                {name = "p_cs_pamphlet_01_s", title = "Pamphlet", price = 700},
                {name = "prop_big_clock_01", title = "Big Clock", price = 500},
                {name = "prop_egg_clock_01", title = "Egg Clock", price = 500},
                {name = "prop_ld_greenscreen_01", title = "Green Screen", price = 100},
                {name = "prop_dart_bd_cab_01", title = "Dart", price = 500},
                {name = "prop_dart_bd_01", title = "Dart 2", price = 500},
                {name = "prop_exercisebike", title = "Exercise Bike", price = 500},
                {name = "p_laz_j02_s", title = "Laz", price = 500},
                {name = "v_res_cherubvase", title = "White Vase", price = 500},
                {name = "v_res_d_paddedwall", title = "Padded Wall", price = 500},
                {name = "prop_dummy_01", title = "Dummy", price = 100},
                {name = "prop_el_guitar_01", title = "E Guitar 1", price = 100},
                {name = "prop_el_guitar_02", title = "E Guitar 2", price = 100},
                {name = "prop_el_guitar_03", title = "E Guitar 2", price = 100},
                {name = "v_res_mbowlornate", title = "Ornate Bowl", price = 300},
                {name = "v_res_mbronzvase", title = "Bronze Vase", price = 300},
                {name = "prop_ceramic_jug_01", title = "Ceramic Jug", price = 100},
                {name = "v_res_m_candle", title = "Candle Large 1", price = 300},
                {name = "v_res_m_candlelrg", title = "Candle Large 2", price = 300},
                {name = "apa_mp_h_acc_candles_06", title = "Candles 1", price = 50},
                {name = "apa_mp_h_acc_candles_05", title = "Candles 2", price = 50},
                {name = "apa_mp_h_acc_candles_04", title = "Candles 3", price = 50},
                {name = "apa_mp_h_acc_rugwools_01", title = "Rug 1", price = 300},
                {name = "apa_mp_h_acc_rugwoolm_01", title = "Rug 2", price = 300},
                {name = "apa_mp_h_acc_rugwooll_04", title = "Rug 3", price = 300},
                {name = "apa_mp_h_acc_rugwooll_03", title = "Rug 4", price = 300},
                {name = "apa_mp_h_acc_rugwoolm_04", title = "Rug 5", price = 300},
                {name = "apa_mp_h_acc_rugwools_03", title = "Rug 6", price = 300},
                {name = "v_res_fh_pouf", title = "Pouf", price = 300},
                {name = "v_res_fh_sculptmod", title = "Sculpture", price = 300},
                {name = "prop_v_5_bclock", title = "Vintage Clock", price = 300},
                {name = "prop_v_15_cars_clock", title = "American Flag Clock", price = 300},
                {name = "prop_sm_19_clock", title = "Modern Clock", price = 300},
                {name = "prop_sports_clock_01", title = "Sports Clock", price = 300},
                {name = "prop_mem_candle_01", title = "Candle 1", price = 300},
                {name = "prop_game_clock_01", title = "Crown Clock", price = 300},
                {name = "prop_game_clock_02", title = "Kronos Clock", price = 300},
                {name = "prop_id2_20_clock", title = "Modern Clock 2", price = 300},
                {name = "ex_office_citymodel_01", title = "CIty name", price = 300},
                {name = "apa_mp_h_acc_dec_head_01", title = "Mask", price = 300},
                {name = "ex_mp_h_acc_vase_06", title = "Vase 1", price = 300},
                {name = "ex_mp_h_acc_vase_02", title = "Red Vase", price = 300},
                {name = "hei_prop_hei_bust_01", title = "Bust", price = 300},
                {name = "prop_arcade_01", title = "Arcade Machine", price = 300},
                {price = 6500, name = 'prop_beer_neon_01', title = 'Neon Sign 1'},
                {price = 6500, name = 'prop_beer_neon_02', title = 'Neon Sign 2'},
                {price = 6500, name = 'prop_beer_neon_03', title = 'Neon Sign 3'},
                {price = 6500, name = 'prop_beer_neon_04', title = 'Neon Sign 3'},
                {price = 6500, name = 'prop_patriotneon', title = 'Neon Sign Patriot'},
                {price = 6500, name = 'prop_barrachneon', title = 'Neon Sign Pussy Beer'}},
 Electronics = {{price = 0, title = 'Lamp', name = 'prop_cd_lamp'},                            --Edit from here
                {price = 180, title = 'Shredder', name = 'v_ret_gc_shred'},
                {price = 80, title = 'Antique telephone', name = 'apa_mp_h_acc_phone_01'},
                {price = 2000, title = 'TV wall white-gray with electronics', name = 'apa_mp_h_str_avunitl_04'},
                {price = 2700, title = 'TV wooden wall with television', name = 'apa_mp_h_str_avunitl_01_b'},
                {price = 3000, title = 'Television with yellow speakers', name = 'apa_mp_h_str_avunitm_01'},
                {price = 3000, title = 'TV with white speakers', name = 'apa_mp_h_str_avunitm_03'},
                {price = 3290, title = 'Television with accessories', name = 'apa_mp_h_str_avunits_01'},
                {price = 690, title = 'TV on a metal table', name = 'apa_mp_h_str_avunits_01'},
                {price = 2500, title = 'Notebook', name = 'bkr_prop_clubhouse_laptop_01a'},
                {price = 2400, title = 'Notebook', name = 'bkr_prop_clubhouse_laptop_01b'},
                {price = 540, title = 'Money counter', name = 'bkr_prop_money_counter'},
                {price = 80, title = 'Large upright fan', name = 'bkr_prop_weed_fan_floor_01a'},
                {price = 240, title = 'Tvsmash', name = 'des_tvsmash_start'},
                {price = 700, title = 'Wall TV', name = 'ex_prop_ex_tv_flat_01'},
                {price = 3500, title = 'Desktop monitor with keyboard', name = 'ex_prop_monitor_01_ex'},
                {price = 4700, title = 'Desktop monitor with keyboard', name = 'ex_prop_trailer_monitor_01'},
                {price = 200, title = 'TV driver', name = 'ex_prop_tv_settop_remote'},
                {price = 220, title = 'TV box', name = 'ex_prop_tv_settop_box'},
                {price = 150, title = 'Table fan', name = 'gr_prop_bunker_deskfan_01a'},
                {price = 8400, title = 'Television with speakers and all equipment', name = 'hei_heist_str_avunitl_03'},
                {price = 170, title = 'telephone landline', name = 'hei_prop_hei_bank_phone_01'},
                {price = 380, title = 'Alarm', name = 'hei_prop_hei_bio_panel'},
                {price = 210, title = 'Keyboard', name = 'hei_prop_hei_cs_keyboard'},
                {price = 890, title = 'Project board', name = 'hei_prop_hei_muster_01'},
                {price = 180, title = 'WIFI', name = 'hei_prop_server_piece_01'},
                {price = 3300, title = 'White notebook', name = 'p_laptop_02_s'},
                {price = 1050, title = 'Safe', name = 'p_v_43_safe_s'},
                {price = 900, title = 'Table Hockey', name = 'prop_airhockey_01'},
                {price = 240, title = 'Portable Radio', name = 'prop_boombox_01'},
                {price = 250, title = 'DVD player', name = 'prop_cctv_cont_03'},
                {price = 330, title = 'CD player', name = 'prop_cctv_cont_04'},
                {price = 90, title = 'PC Mouse', name = 'prop_cs_mouse_01'},
                {price = 90, title = 'Wall clock', name = 'prop_game_clock_01'},
                {price = 80, title = 'Wall clock black', name = 'prop_game_clock_02'},
                {price = 3400, title = 'HiFi system', name = 'prop_hifi_01'},
                {price = 150, title = 'square clock', name = 'prop_hotel_clock_01'},
                {price = 150, title = 'Clock', name = 'prop_id2_20_clock'},
                {price = 3400, title = 'Nikon Handheld Camera', name = 'prop_ing_camera_01'},
                {price = 170, title = 'White keyboard', name = 'prop_keyboard_01a'},
                {price = 160, title = 'Router', name = 'prop_ld_armour'},
                {price = 170, title = 'Old monitor', name = 'prop_ld_monitor_01'},
                {price = 130, title = 'Small old monitor', name = 'prop_monitor_01b'},
                {price = 400, title = 'RETRO monitor', name = 'prop_monitor_03b'},
                {price = 590, title = 'Monitor', name = 'prop_monitor_w_large'},
                {price = 480, title = 'Repráček', name = 'prop_mp3_dock'},
                {price = 1400, title = 'White PC', name = 'prop_pc_01a'},
                {price = 1800, title = 'Black PC', name = 'prop_pc_02a'},
                {price = 500, title = 'Mobile', name = 'prop_phone_ing'},
                {price = 400, title = 'Mobile', name = 'prop_phone_ing_02'},
                {price = 400, title = 'Mobile', name = 'prop_phone_ing_02_lod'},
                {price = 330, title = 'Mobile', name = 'prop_phone_ing_03'},
                {price = 1000, title = 'RETRO radio', name = 'prop_radio_01'},
                {price = 300, title = 'Small speaker', name = 'prop_speaker_05'},
                {price = 1000, title = 'Speaker', name = 'prop_speaker_06'},
                {price = 1900, title = 'Speaker', name = 'prop_speaker_08'},
                {price = 200, title = 'Old TV', name = 'prop_trev_tv_01'},
                {price = 500, title = 'Old TV', name = 'prop_tv_03'},
                {price = 300, title = 'Old TV', name = 'prop_tv_01'},
                {price = 400, title = 'RETRO TV', name = 'prop_tv_04'},
                {price = 270, title = 'Old TV', name = 'prop_tv_06'},
                {price = 650, title = 'Plasma big screen', name = 'prop_tv_flat_01'},
                {price = 1250, title = 'Plasma thin TV', name = 'prop_tv_flat_01_screen'},
                {price = 600, title = 'Plasma small television', name = 'prop_tv_flat_02'},
                {price = 500, title = 'Plasma small television', name = 'prop_tv_flat_02b'},
                {price = 200, title = 'Small TV with stand', name = 'prop_tv_flat_03'},
                {price = 300, title = 'Small TV on the wall', name = 'prop_tv_flat_03b'},
                {price = 9200, title = 'Television Michael 50cm', name = 'prop_tv_flat_michael'},
                {price = 1000, title = 'Little US Clock', name = 'prop_v_15_cars_clock'},
                {price = 9000, title = 'Professional camera', name = 'prop_v_cam_01'},
                {price = 4700, title = 'VET player RETRO', name = 'prop_vcr_01'},
                {price = 900, title = 'Mixing desk', name = 'v_club_vu_deckcase'},
                {price = 500, title = 'RETRO Laptop', name = 'v_ind_ss_laptop'},
                {price = 500, title = 'CD seda', name = 'v_res_cdstorage'},
                {price = 300, title = 'Ipod', name = 'v_res_ipoddock'},
                {price = 800, title = 'Silver Monitor', name = 'v_res_monitorwidelarge'},
                {price = 400, title = 'Mouse and as a gift pad', name = 'v_res_mousemat'},
                {price = 100, title = 'PC Headphones', name = 'v_res_pcheadset'},
                {price = 100, title = 'PC speaker', name = 'v_res_pcspeaker'},
                {price = 500, title = 'VHS white RETRO player', name = 'v_res_vhsplayer'},
                {price = 800, title = 'Vacuum Cleaner', name = 'v_res_vacuum'},
                {price = 100, title = 'Stapler', name = 'v_ret_gc_staple'},
                {price = 1900, title = 'Hardisk', name = 'xm_prop_x17_harddisk_01a'},
                {price = 5300, title = 'Computer', name = 'xm_prop_x17_res_pctower'},
                {price = 3290, title = 'Plasma TV', name = 'xm_prop_x17_tv_flat_01'},
                {price = 3600, title = 'Plasma TV', name = 'xm_prop_x17_tv_flat_02'},
                {price = 14000, title = 'Jukebox', name = 'bkr_prop_clubhouse_jukebox_01b'},
                {price = 10, title = 'USB', name = 'hei_prop_hst_usb_drive'},
                {price = 270, title = 'Flashlight', name = 'p_cs_police_torch_s'},
                {price = 100, title = 'Microphone', name = 'p_ing_microphonel_01'},
                {price = 160, title = 'Radio', name = 'prop_tapeplayer_01'},
                {price = 4500, title = 'Multifunction Laser Printer', name = 'prop_printer_01'},
                {price = 11200, title = 'Multifunction Laser Printer', name = 'prop_printer_02'},
                {price = 20300, title = 'Jukebox 2', name = 'prop_50s_jukebox'},
                {price = 2120, title = 'Arcade games', name = 'prop_arcade_01'},
                {price = 1400, title = 'Safe', name = 'prop_ld_int_safe_01'},
                {price = 380, title = 'Astronomical Clock', name = 'prop_v_5_bclock'},
                {price = 22200, title = 'Table with three monitors', name = 'xm_prop_base_staff_desk_01'},
                {price = 17900, title = 'Table with three monitors', name = 'xm_prop_base_staff_desk_02'},
                {price = 150, title = 'Napkin machine', name = 'prop_handdry_01'},
                {price = 270, title = 'Washing Machine', name = 'prop_washer_02'},
                {price = 100, title = 'Washing machine with its years', name = 'prop_washer_03'},
                {price = 70, title = 'RETRO washing machine', name = 'v_ret_fh_dryer'}},
  Tables = {{price = 560, title = 'Glass table', name = 'apa_mp_h_din_table_04'},
            {price = 500, title = 'Glass table', name = 'apa_mp_h_din_table_11'},
            {price = 530, title = 'Glass table', name = 'apa_mp_h_tab_sidelrg_07'},
            {price = 420, title = 'Black Round Table', name = 'apa_mp_h_tab_sidelrg_04'},
            {price = 1600, title = 'Glass table', name = 'apa_mp_h_tab_sidelrg_01'},
            {price = 5700, title = 'Decorative glass table', name = 'apa_mp_h_tab_sidelrg_02'},
            {price = 260, title = 'Black coffee table', name = 'apa_mp_h_yacht_coffee_table_01'},
            {price = 420, title = 'Square table', name = 'apa_mp_h_yacht_side_table_01'},
            {price = 340, title = 'Small table', name = 'gr_dlc_gr_yacht_props_table_01'},
            {price = 470, title = 'Long table', name = 'gr_dlc_gr_yacht_props_table_02'},
            {price = 1000, title = 'Particleboard table', name = 'prop_rub_table_01'},
            {price = 700, title = 'Particleboard dining table', name = 'prop_rub_table_02'},
            {price = 700, title = 'TV table', name = 'prop_tv_cabinet_03'},
            {price = 300, title = 'TV table', name = 'prop_tv_cabinet_04'},
            {price = 800, title = 'TV table', name = 'prop_tv_cabinet_05'},
            {price = 5300, title = 'Black modern table', name = 'v_ilev_liconftable_sml'},
            {price = 4100, title = 'Bar', name = 'xm_prop_lab_desk_01'}},
  Sofas = {{price = 2150, title = 'Couch with pillows', name = 'prop_couch_01'},
           {price = 2500, title = 'Padded bench', name = 'prop_wait_bench_01'},
           {price = 2400, title = 'White leather sofa', name = 'xm_lab_sofa_01'}},
  Kitchen = {{price = 80, title = 'Kitchen scale', name = 'bkr_prop_coke_scale_01'},
             {price = 500, title = 'Home coffee maker', name = 'prop_coffee_mac_02'},
             {price = 520, title = 'Automatic juice mixer', name = 'prop_juice_dispenser'},
             {price = 200, title = 'White wall phone', name = 'prop_office_phone_tnt'},
             {price = 230, title = 'Fruit Blender', name = 'p_kitch_juicer_s'},
             {price = 150, title = 'Kettle', name = 'prop_kettle_01'},
             {price = 260, title = 'Crushing machine', name = 'prop_slush_dispenser'},
             {price = 70, title = 'Coffee pot', name = 'xm_prop_x17_coffee_jug'},
             {price = 370, title = 'Mini bar fridge', name = 'prop_bar_fridge_03'},
             {price = 8, title = 'Plastic red cup', name = 'apa_prop_cs_plastic_cup_01'},
             {price = 100, title = 'Trash', name = 'prop_bin_10a'},
             {price = 400, title = 'Universal Cleaner', name = 'prop_blox_spray'},
             {price = 200, title = 'Green bucket', name = 'prop_buck_spade_05'},
             {price = 400, title = 'Blue bucket', name = 'prop_buck_spade_06'},
             {price = 200, title = 'Red bucket', name = 'prop_buck_spade_07'},
             {price = 7, title = 'Cups', name = 'prop_food_cups2'},
             {price = 4, title = 'White Cup', name = 'prop_mug_02'},
             {price = 80, title = 'Bowl with donut lid', name = 'v_res_cakedome'},
             {price = 100, title = 'Loose tea container', name = 'v_res_fa_pottea'},
             {price = 300, title = 'Deep Plate', name = 'v_res_mbowl'},
             {price = 20, title = 'Paper napkins', name = 'v_ret_ta_paproll'},
             {price = 40, title = 'Glasses', name = 'p_w_grass_gls_s'},
             {price = 30, title = 'Glasses', name = 'prop_cocktail'},
             {price = 60, title = 'Knife', name = 'prop_cs_bowie_knife'}},
  Bedroom = {{price = 330, title = 'Single bed', name = 'v_res_msonbed'},
             {price = 1000, title = 'Double bed', name = 'p_lestersbed_s'},
             {price = 600, title = 'Double bed', name = 'p_v_res_tt_bed_s'},
             {price = 2400, title = 'Double modern bed', name = 'apa_mp_h_bed_double_08'},
             {price = 2100, title = 'Double modern bed', name = 'apa_mp_h_bed_wide_05'},
             {price = 2200, title = 'Double modern bed', name = 'apa_mp_h_yacht_bed_02'},
             {price = 700, title = 'Single sofa bed', name = 'ex_prop_exec_bed_01'},
             {price = 3100, title = 'Double modern bed', name = 'hei_heist_bed_double_08'},
             {price = 4400, title = 'Chest of drawers', name = 'apa_mp_h_bed_chestdrawer_02'},
             {price = 400, title = 'RETRO wardrobe', name = 'apa_mp_h_str_shelffloorm_02'},
             {price = 100, title = 'RETRO chest of drawers low', name = 'apa_mp_h_str_sideboardl_11'},
             {price = 250, title = 'Gray-white low cabinet', name = 'apa_mp_h_str_sideboardl_13'},
             {price = 700, title = 'Wooden chest of drawers', name = 'apa_mp_h_str_sideboardl_14'},
             {price = 500, title = 'Wood brindle feather duster', name = 'apa_mp_h_str_sideboardm_02'},
             {price = 300, title = 'Iron open cabinet', name = 'p_cs_locker_01'},
             {price = 300, title = 'Iron used closed cabinet', name = 'p_cs_locker_01_s'}}}
